spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: USER-MS
          uri: lb://USER-MS
          predicates:
            - Path=/api/users/**

server:
    port: 8084

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka/
